export const FETCH_CONTRACT_DETAILS = 'FETCH_CONTRACT_DETAILS';
export const FETCH_TASKS = 'FETCH_TASKS';
export const SUBMIT_OUTCALL_COMMENT = 'ADD_OUTCALL_COMMENT';
export const EDIT_OUTCALL_COMMENT = 'EDIT_OUTCALL_COMMENT';
export const OUTCALL_STATUS_COMMENT_UPDATED = 'OUTCALL_STATUS_COMMENT_UPDATED';
