export const LOG_WERKS_REQUEST_LIST_FETCHED = 'LOG_WERKS_REQUEST_LIST_FETCHED';
export const LOG_WERKS_REQUEST_BLANKED = 'LOG_WERKS_REQUEST_BLANKED';
export const LOG_WERKS_REQUEST_FETCHED = 'LOG_WERKS_REQUEST_FETCHED';
export const LOG_WERKS_REQUEST_ITEM_BLANKED = 'LOG_WERKS_REQUEST_ITEM_BLANKED';
export const LOG_MATNRS_FETCHED = 'LOG_MATNRS_FETCHED';
export const LOG_MATNRS_LOADING = 'LOG_MATNRS_LOADING';
export const LOG_INVOICES_FETCHED = 'LOG_INVOICES_FETCHED';
