export const CREATE_NEW_TASK = 'CREATE_NEW_TASK';
export const DTSKC_FETCH_REFERENCES = 'DTSKC_FETCH_REFERENCES';
export const DTSKC_FETCH_ASSIGNEES = 'DTSKC_FETCH_ASSIGNEES';
export const DTSKC_ASSIGNEE_MODAL_TOGGLE = 'DTSKC_ASSIGNEE_MODAL_TOGGLE';
